#!/bin/sh

$(npm bin)/grpc_tools_node_protoc \
    --proto_path=proto \
    --plugin=$(npm bin)/protoc-gen-ts_proto \
    --ts_proto_out=src/protogen \
    --ts_proto_opt=outputServices=grpc-js \
    --ts_proto_opt=forceLong=number \
    --ts_proto_opt=esModuleInterop=true \
    --ts_proto_opt=outputClientImpl=false \
    --ts_proto_opt=addGrpcMetadata=true \
    proto/*.proto
